hash-format = "sha256"

[[files]]
file = "config/custom-hud/profile1.txt"
hash = "10d7691ad85825af13bb637bb96ea7235e4e4886dbc48b490d6d34c7b9476265"

[[files]]
file = "mods/jcm.pw.toml"
hash = "FCA56F05F533F78D2DC0BDCDFAE3CCC9EC899FF238009BA2FB4A87A0B046904B"

[[files]]
file = "mods/mtrlondon.pw.toml"
hash = "5E40ED3A7A1FAF1F036CCAF47CEFBEFB842B1A19263958B45C9A080C532F6F47"

[[files]]
file = "mods/mtr.pw.toml"
hash = "930418A9B72409C340749A238B03EE461FFB4D4C27C659C6952CB89DC94F445F"

[[files]]
file = "mods/Slideshow.pw.toml"
hash = "C860B41A8F102FD13E2DC25E7B9C4C748C73AF6DB3F37558155A61E00E16EEC0"

[[files]]
file = "mods/banhammer.pw.toml"
hash = "479090c70c1dfcbcd50516500cc99df70aede85546d511b8e03644ea6eb59656"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "f16a5795a6ba42c12667f25f67ad0d50f2e384a13e1378d68f2daf6464f65293"
metafile = true

[[files]]
file = "mods/blossomwarps.pw.toml"
hash = "d011dd222ff900c9bd1eea73a45665e350c6736027f7a16a5d78a65b96629614"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "079e7613c7440aa11de9a74860ce30f6f7c9e43ebfe0e297fb546c82771c51dd"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "b499c0f69d4078ebfaa7755db796e3667e536cce8bff0e7290bc4071e6f14905"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "931fa7587facbc9b334c7539722b2dacaac520f253ebfbc5b87665d5abbcea77"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "ef1882c0ab8f4a594fbf29168e55ad491641d35ec438e84929bf5e37e41f2ec4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "45f0a2c35bc9aa87baf55ccf912a3c151167192468abba647858d421c24354d3"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "ac2807a1056b7dc795f2cd27dbc1ca8f14ad8c199dc78f0038e9f9245a35335b"
metafile = true

[[files]]
file = "mods/customhud.pw.toml"
hash = "9ad5b4dc074771f997346fc7f85165862150e3a10c465a5a64ad630bfe386218"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8435fe34f180c963234295c6bf8de293b3450d74f2ab74389ac9bdf198d84612"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/filters-api.pw.toml"
hash = "b9480e9b507930881bda195d5ddebe107084261e5afcd1ab61cc107bef116c61"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "4eddbfb450a37b85a1ac710d3ecb51f4e527130bd453f8a16f067210b2767692"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "0f83be0761e0014686517c20f2850242152dd7a26e87088d869028bc40a8a125"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "db812a9b3a4a8ea011eedc44bdc4df13a1f3cfb67130fe57d3990342566d03a8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "96cafb1b451ce577f0a74045704c2f51c3ab34d63fbba81df669c21646d33bff"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "104c4342e55bbeb5c4714dd7fe960490c6e09fff80cd5cf7dea14689bc75007c"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "57fc1c61ba53059ccb27647cf44d4b8671ccf284fcd869ec1b6c04a94eb8335e"
metafile = true

[[files]]
file = "mods/minimotd.pw.toml"
hash = "2d18c73b937ef60dab3340ec8fd93107f6ff3448b22cf064a96d98361a45eb53"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "07114208e332aa5fbc3e7144c2bac58ea74e50d4eaeac2b6c6cc5c41286bb335"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "56365fcf55b2679a8f2ceefe5c3f949854d13945963a421d178145d0551b2fac"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "e5e76b305f6e8fd611fb70695f42014c62e5f46b926d626eaf5ca0c78e394c5c"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "181bfe0cfc3bd30e07dc328dac9fed42705ef5cd1977ee86e48942e8d0e47ee1"
metafile = true

[[files]]
file = "mods/resourcepackupdater.pw.toml"
hash = "E97CADCA15C2EA55B674314263ED674827DD84F9B5609EBA507D2F5A40454A41"

[[files]]
file = "mods/russian-metro-addon.pw.toml"
hash = "73a9839e338fbfb4d8b63eb3a274daf8557fab45932085b371dec3ce8cbf5577"
metafile = true

[[files]]
file = "mods/sdlink.pw.toml"
hash = "88abd793d09e46770557b81f13960492227317a08d856db9c099ce6c61d7f731"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "cab2936a9939350acb6733ebe405e110743f5dfef4afec31ba0d34d759819ced"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "521c8241593053f877a89ce447c64392c3619e16c2001b3cac7d72cbde8392d0"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c6a5c6afaf276bde5c35adb34e21155112b7defd08b83d95a81e435bc6530c42"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "75e3fb7d66b8e29bfc31b39e123c62c67fcb11d4614f2c6ac16df18a1b5e3eaf"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "d0aa439438069d14311f23a19678e28fc8763b0e8aa9f6fc5b3cdc68556d6f0d"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
hash = "b8f43a50939082d1d771497405b8c69a9a4a7fd8b32fa8828bafb723e4eb5e21"
metafile = true

[[files]]
file = "mods/takeaseat.pw.toml"
hash = "82e0ea125db1f63edea6ef75bff309cb9daeea0329070e5b9d1a7c43656d6953"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/tianjin-metro.pw.toml"
hash = "01766147ff9b9877712d1a5ac3c8245282c41d3cc510567d3a57a525360c75a1"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "4427adf110cf4b328290bd6e7cad7b45fe6bf742e3efd32c13dee5a9e450d5e0"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "8a7bab663c386b0e31a5730d4c585baae859ea47ff716fa30fd8d0103ccba1a4"
metafile = true

[[files]]
file = "mods/worldeditcui-fabric.pw.toml"
hash = "1ba66daecd4b33b1728b12acd2d9729bc07ccfdfe9bc41ffc9f09adfe9568577"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "c658bdc0ecb6b7c47cdf44e1d06af9077d0abc75e62cb89303ac72c99408c08c"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "07f5f332fa5883f1d4caf9c5a88439590e24ae60f9b8b4cb9f25da3bcf5d2795"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3e60658ff7a05981f63290f5e467abe8816bf1bd24a060f5a190300dcd9181b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "6d5f8b20e43d731d0df2f6d94c861e478d28062e863ca18ef8812894b308d070"
metafile = true

[[files]]
file = "servers.dat"
hash = "02d7843d754ee03ca2fc8b2499d75d734de20feaba93df7767692fd84ee0738a"
